title: jeremedia
author: Jeremy Roush
email: j@jeremedia.com
description: Sprinkles of things
url: "https://jeremedia.github.io" # your GitHub Pages URL will go here
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Social media
twitter_username: jeremedia
github_username: jeremedia

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/